repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        name: ESLint
        files: \.(js|ts|jsx|tsx)$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # актуальна стабільна версія flake8
    hooks:
      - id: flake8
        name: Flake8 (Python Linter)
        files: \.(py)$


  - repo: local
    hooks:
        - id: phpcs
          name: PHP_CodeSniffer
          entry: ./vendor/bin/phpcs
          language: system
          types: [ php ]
          args: [ '--standard=PSR12' ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        name: Mypy (static type checking for Python)
        files: \.(py)$

  - repo: local
    hooks:
      - id: handle-wh-hook
        name: Check handleWebhook formatting
        entry: python hooks/handle_wh_hook.py
        language: python
        files: \.js$
